FROM r-base:latest
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        pandoc r-cran-rmarkdown rsync 

RUN apt-get install curl && curl https://rclone.org/install.sh | bash

COPY rclone.config.template /root/.config/rclone/rclone.conf

COPY reader.R /root/reader.R
COPY rcloneish.sh .
RUN chmod +x rcloneish.sh

CMD ["bash"]
