FROM rocker/r-base:latest

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	libssl-dev libcurl4-openssl-dev

RUN Rscript -e 'utils::install.packages("googledrive")'

CMD ["bash"]
