---
title: "Linear regression  for machine learning lab"
output:
  html_document:
    df_print: paged
---
Learning objectives.

- Split data into **training** and **test** data in ``R``
- Train/fit a linear regression model in ``R``
- Evaluate **prediction performance** of a linear regression model


### Analysis
You will recreate and extend the analysis of the brain weight data.

1. Read in (``red.table``) the Brain weight dataset. Examine (``head``) and summarize (``summary``) the data.

2. Convert Sex and Age to factor variables so that ``lm`` can properly deal with them.

3. Split the data into training (70%) and test (30%) sets.

4. Fit a linear regression model with brain weight as the outcome and head Size, Sex, and Age as predictors. What is the interpretation of the coefficients for Sex and Age? Compute the training and test RMSE and $R^2$. Does adding Age improve *prediction performance* over the model with Sex and Head size alone?

5. Explore whether fitting a linear regression model with separate intercepts and separate slopes for $20 \le$ Age $<$ 46 and Age $\ge$ 46 improves prediction performance (hint: you can, for example, specify an interaction between Sex and Head size including `` Head.Size:Age`` in the model formula.




