---
title: "Model selection"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Learning objectives.

- Perform model selection in ``R``.
- Write ``R`` functions.

Percent of body fat is a health indicator that can be measured by relatively costly methods such as underwater weighing (gold-standard) and dual energy x-ray absorptiometry. ([You can check here to learn more about body fat and its importance](http://halls.md/body-fat-percentage-formula/)) The goal of this Lab problem is to develop a model for predicting body fat based on readily available features like BMI, sex and age without requiring involved and costly measurements. 
    a. Load the body fat data (posted on blackboard) using the ``read.csv`` function. ``read.csv`` works just like ``read.table`` but reads comma delimited files instead. Make sure you use the ``header = TRUE`` option to read in the variable names in the first row of the file.
    b. Check the structure of the body fat data with ``head().`` Notice that there are missing values denoted as ``NA``.
    c. For this Lab you will only use the 4 variables: total percent body fat (``dxdtopf``), gender (``riagendr``), age in years (``ridageyr``), and body mass index BMI (``bmxbmi``). Create a new data.frame ``body.fat4`` with just these four variables. Hint: you can extract named columns/variables from a data frame as follows: ``your.data.frame[, c('dxdtopf', 'riagendr', 'ridageyr', 'bmxbmi')]``
    d. Rename the variables to ``body.fat``, ``sex``, ``age``, and ``bmi``. Hint: you can use: ``colnames(body.fat4) <- c('body.fat', 'sex', 'age', 'bmi')``
    e. Recode `sex` as a factor variable (1=Male 2=Female) using ``factor``.
    f. How many observations/rows are there with no missing values in *any* of the 4 variables (complete cases). Hint: use the `complete.cases` function.
    g. Remove any incomplete cases. Hint: this is equivalent to retaining only the complete cases.
    h. Split the data into a training (60%), validation (20%), and testing set (20%) (set the seed with ``set.seed(2018)`` so the split can be reproduced.)
    i. Fit the linear model ``body.fat ~ bmi`` using the training set. Compute the training and validation RMSE and  $R^2$ using the ``rmse`` function from the lecture and the ``Rsq`` function you wrote.
    j. Repeat i. for models with the following predictors:
        + ``bmi``, ``age``, ``sex``
        + ``bmi``, ``bmi^2``, ``age``, ``age^2``, ``sex``. (Remember you need to enclose in transformed variables with ``I()``, e.g. ``I(bmi^2)``). Would it make sense to include ``sex^2``?
      Which model would you choose? Compute final estimates of prediction performance for your selected model using the test data.

3. Repeat steps h-j using a different random split (set the seed to a different value) into training (60%), validation (20%), and testing set (20%). Do you get similar results? Do you choose the same model? Are the final test prediction metrics (RMSE and $R^2$ similar)?. Comment on the reliability of splitting the data into training, validation, and test to perform model selection when you have a modest sample size. 

