on:
  schedule:
    cron: '0-59/30 0-23 * * *' # Every half hour

env:
  cntr: uscbiostats/lasbest-gdrive:latest
  GD_TOKEN: ${{ secrets.GD_TOKEN }}
  GD_DRIVE_PATH: ${{ secrets.GD_DRIVE_PATH }}

jobs:
  download-drive:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${cntr}

      - name: Download
        run: |
          docker run --rm -i -v$(pwd):/gdrive/ \
            -e GD_TOKEN=${GD_TOKEN} \
            -e GD_DRIVE_PATH=${GD_DRIVE_PATH} ${cntr} ./rcloneish.sh copy mydrive: /gdrive/gd

      - name: List files
        run: ls -R

