# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Deploying w docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '5-59/15 * * * *' # Every hour from 

jobs:
  build:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        include:
        - name: latest
          cntr: uscbiostats/lasbest-website:latest

    steps:
      - uses: actions/checkout@v2

      - name: Container
        run: docker pull ${{ matrix.cntr }}

      - name: SessionInfo
        run: docker run --rm -i -v ${PWD}:/mnt -w /mnt ${{ matrix.cntr }} R -q -e 'sessionInfo()'

      - name: Build
        run: docker run --rm -i -v $(pwd):/mnt -w /mnt -e CI=true ${{ matrix.cntr }} make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/_site

